### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by fflorent**
- Add config panel
- Remove change_url (cleanup)

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by fflorent** [comment]
!testme

**Comment by fflorent** [comment]
!testme

**Comment by OniriCorpe** [comment]
@fflorent
[Fix typo](https://github.com/YunoHost-Apps/mautrix_discord_ynh/pull/4/commits/a5de7e5be7cf31ab13ac74a1de14811d237e14e3)

ah yes sorry 😬

**Comment by fflorent** [comment]
No problem!

**Comment by fflorent** [comment]
!testme

**Pull request merged**
